name:                odmatrix-sim
version:             0.1.0.1
github:              "renecura/odmatrix-sim"
license:             BSD3
author:              "Rodrigo René Cura"
maintainer:          "rodrigo.renecura@gmail.com"
copyright:           "2018 Rodrigo René Cura"

extra-source-files:
- README.md
#- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/renecura/odmatrix-sim#readme>

dependencies:
- base >= 4.7 && < 5
- random
- mtl
- random-shuffle
- hmatrix
# - odmatrix
# - containers
# - bytestring
# - array
# - MissingH

library:
  source-dirs: src
  exposed-modules:
    ODMatrix.Sim.BusState
  other-modules:
    ODMatrix.Sim.Poisson
    
  

    
    

executables:
  odmatrix-sim-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - odmatrix-sim

# executables:
#   odmatrix-sim-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - odmatrix-sim
#     - ConfigFile
#     - array
#     - hmatrix
#     - random

# tests:
#   odmatrix-sim-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - odmatrix-sim
